
## DO NOT EDIT THIS FILE


def print_euf_formula(f):
    print("%% EUF-FORMULA:", f)

def print_pl_formula(f):
    print("%% PL-FORMULA:", f)

def print_clauses(clause_list):
    print("%% CLAUSE-LIST:", clause_list)

def print_clause_added(clause):
    print("%% CLAUSE-ADDED:", clause)

